### ISSUE TITLE
ISSUE 단위로 BRANCH 생성해서 PR 요청해주세요.

### ISSUE THREAD

**Issue by tuyy** [yeongyeoncho91/BaseBallGame#6]
@yeongyeoncho91 
```ISSUE_{issue_number}``` 로 브랜치를 생성하고 Pull requests로 코드 리뷰 요청 부탁드립니다
추가로 궁금한 점 있으면 코멘트 남겨주시고, 특이사항 없으면 이 이슈 닫아주세요.

**Comment by yeongyeoncho91** [comment]
@tuyy 
네 알겠습니다!
